language: java
jdk:
  - oraclejdk11
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt install python3-dev python3-pip
  - pip install --upgrade pip
  - pip3 install --user --upgrade tensorflow
  - python3 -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([100, 100])))"