language: java
jdk:
  - oraclejdk11
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt install python3-dev python3-pip
  - sudo pip3 install --upgrade pip3
  - pip3 install --user --upgrade tensorflow