language: java
jdk:
  - openjdk11
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt install python3-dev python3-pip
  - sudo apt-get install -y python3-setuptools
  - sudo python3 -m pip install --upgrade pip
  - python3 -m pip install --user tensorflow==1.14.0
  - python3 -c "import tensorflow as tf; op = tf.constant(\"hello world\"); sess=tf.Session(); print(sess.run(op))"
  - sudo apt-get install xvfb
  - sudo Xvfb :1 -screen 0 1024x768x24 </dev/null &
  - export DISPLAY=":1"

