language: java
jdk:
  - oraclejdk11
before_install:
  - sudo apt-get update
  - sudo apt-get install python
  - sudo pip install --upgrade pip
  - sudo apt install python-dev python-pip
  - pip install --user --upgrade tensorflow