machine:
  coreFraction: 0.7
  coreMinimum: 1
  coreMaximum: 32
  logLevel: INFO
tree:
  actionGenerator:
    type: fixed_sequence
    repeatedActions:
      - distribution:
          type: normal
          mean: 10.0
          standardDeviation: 2.0
        none: '2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 '
      - distribution:
          type: normal
          mean: 25.0
          standardDeviation: 3.0
        wo: '5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
        31 32 33 34 '
      - distribution:
          type: normal
          mean: 10.0
          standardDeviation: 2.0
        none: '2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 '
      - distribution:
          type: normal
          mean: 25.0
          standardDeviation: 3.0
        qp: '5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
        31 32 33 34 '
    actionExceptions:
      depth0:
        distribution:
          type: normal
          mean: 5.0
          standardDeviation: 1.0
        none: '1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
          27 28 29 30 31 32 33 34 '
      depth1:
        distribution:
          type: normal
          mean: 34.0
          standardDeviation: 2.0
        wo: '5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
          30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 '
      depth2:
        distribution:
          type: normal
          mean: 24.0
          standardDeviation: 2.0
        none: '1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
          27 28 29 30 31 32 33 34 '
      depth3:
        distribution:
          type: normal
          mean: 49.0
          standardDeviation: 2.0
        qp: '5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
          30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 '
searchOperations:
- stage:
    type: grouping
    treeStages:
    - type: max_depth
      maxDepth: 100
      maxGames: 2000
    - type: value_update
      valueFunction:
        type: tflow_state_only
        fileName: src/main/resources/tflow_models/test.pb
        gameTemplate:
          type: default
        hiddenLayerSizes:
        - 128
        - 64
        additionalNetworkArgs: []
        activeCheckpoint: null
        inputSize: 72
        outputSize: 1
      checkpointName: src/main/resources/tflow_models/checkpoints/checkpoint_name
      excludeLeaves: false
      updateGraphicalLabels: true
  sampler:
    type: ucb
    evaluationFunction:
      type: constant
      constantValue: 0
    rolloutPolicy:
      type: decaying_horizon
      evaluationFunction:
        type: distance
      rolloutController:
        type: random
      maxTimesteps: 200
      rolloutActionGenerator:
        type: fixed_sequence
        repeatedActions:
        - distribution:
            type: normal
            mean: 12.0
            standardDeviation: 5.0
          none: '2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 '
        - distribution:
            type: normal
            mean: 20.0
            standardDeviation: 5.0
          wo: '15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 '
        - distribution:
            type: normal
            mean: 12.0
            standardDeviation: 5.0
          none: '2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 '
        - distribution:
            type: normal
            mean: 20.0
            standardDeviation: 5.0
          qp: '15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 '
    explorationConstant: 3.0
    explorationRandomFactor: 2.0
  saver:
    type: null
    saveInterval: 0
    savePath:
  repetitionCount: 100
ui:
  type: full
  tabbedPanes:
  - type: runner_animated_transformed
    name: Run Animation
  - type: runner_snapshot
    name: State Viewer
    numHistoryStatesDisplay: 25
  - type: runner_comparison
    name: State Compare
    maxNumStatesToShow: 50
  - type: plot_states
    name: State Plots
    numberOfPlots: 6
  - type: futures_pie
    name: Viable Futures
  - type: depth_histogram
    name: Leaf depth distribution
  - type: plot_controls
    name: Controls Plots
    numberOfPlots: 6
  - type: plot_single_run
    name: Single Run Plots
    numberOfPlots: 6
  - type: plot_transformed
    transformer:
      type: pca
      transformPCAComponents:
        transformPCAComponents: '0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
          20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
          44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
          68 69 70 71 '
      outputSize: 72
      name: PCA 72
    name: PCA Plots
    plotsPerView: 6
    numberOfPlots: 6
  - type: plot_transformed
    transformer:
      type: autoencoder
      graphFile: src/main/resources/tflow_models/AutoEnc_72to12_6layer.pb
      outputSize: 12
      name: AutoEnc 12
    name: Autoenc Plots
    plotsPerView: 6
    numberOfPlots: 6
