machine:
  coreFraction: 0.5
  coreMinimum: 1
  coreMaximum: 20
  logLevel: "DEBUG"
searchOperations:
- stage: !<max_depth>
    maxDepth: 10
    maxGames: 10000
  sampler: !<ucb>
    evaluationFunction: !<constant>
      constantValue: 5.0
    rolloutPolicy: !<end_score>
      evaluationFunction: !<constant>
        constantValue: 10.0
      controller: !<null> {}
      maxTimesteps: 2147483647
      failureMultiplier: 1.0
    c: 5.612214
  saver: !<null> {}
  repetitionCount: 0
ui:
  ui: !<full> {}
