machine:
  coreFraction: 0.7
  coreMinimum: 1
  coreMaximum: 32
  logLevel: INFO
game:
  type: default #delay_embedded
  # timestepDelay: 1
  # numDelayedStates: 1
  # stateType: DIFFERENCES
tree:
  actionGenerator:
    type: fixed_sequence
    repeatedActions:
    - '@type': CommandQWOP
      distribution:
        type: normal
        mean: 8.0
        standardDeviation: 5.0
      none: '4 5 6 7 8 9 10 11 12 13 14 15 16 17'
    - '@type': CommandQWOP
      distribution:
        type: normal
        mean: 4.0
        standardDeviation: 3.0
      w: '1 2 3 4 5 6 7 8'
    - '@type': CommandQWOP
      distribution:
        type: normal
        mean: 9.0
        standardDeviation: 3.0
      wo: '1 2 3 4 5 6 7 8 9 10'
    - '@type': CommandQWOP
      distribution:
        type: normal
        mean: 4.0
        standardDeviation: 3.0
      w: '1 2 3 4 5 6 7 8'
    - '@type': CommandQWOP
      distribution:
        type: normal
        mean: 4.0
        standardDeviation: 3.0
      wo: '1 2 3 4 5 6 7 8'
    - '@type': CommandQWOP
      distribution:
        type: normal
        mean: 4.0
        standardDeviation: 3.0
      w: '1 2 3 4 5 6 7 8'
    - '@type': CommandQWOP
      distribution:
        type: normal
        mean: 4.0
        standardDeviation: 3.0
      wo: '1 2 3 4 5 6 7 8'
    - '@type': CommandQWOP
      distribution:
        type: normal
        mean: 8.0
        standardDeviation: 5.0
      none: '4 5 6 7 8 9 10 11 12 13 14 15 16 17'
    - '@type': CommandQWOP
      distribution:
        type: normal
        mean: 4.0
        standardDeviation: 3.0
      q: '1 2 3 4 5 6 7 8'
    - '@type': CommandQWOP
      distribution:
        type: normal
        mean: 9.0
        standardDeviation: 3.0
      qp: '1 2 3 4 5 6 7 8 9 10'
    - '@type': CommandQWOP
      distribution:
        type: normal
        mean: 4.0
        standardDeviation: 3.0
      q: '1 2 3 4 5 6 7 8'
    - '@type': CommandQWOP
      distribution:
        type: normal
        mean: 4.0
        standardDeviation: 3.0
      qp: '1 2 3 4 5 6 7 8'
    - '@type': CommandQWOP
      distribution:
        type: normal
        mean: 4.0
        standardDeviation: 3.0
      q: '1 2 3 4 5 6 7 8'
    - '@type': CommandQWOP
      distribution:
        type: normal
        mean: 4.0
        standardDeviation: 3.0
      qp: '1 2 3 4 5 6 7 8'
    actionExceptions:
      depth0:
        '@type': CommandQWOP
        distribution:
          type: normal
          mean: 5.0
          standardDeviation: 1.0
        none: '7'
      depth1:
        '@type': CommandQWOP
        distribution:
          type: normal
          mean: 34.0
          standardDeviation: 2.0
        wo: '49'
      depth2:
        '@type': CommandQWOP
        distribution:
          type: normal
          mean: 24.0
          standardDeviation: 2.0
        none: '2'
      depth3:
        '@type': CommandQWOP
        distribution:
          type: normal
          mean: 49.0
          standardDeviation: 2.0
        qp: '25'
      depth4:
        '@type': CommandQWOP
        distribution:
          type: normal
          mean: 5.0
          standardDeviation: 1.0
        none: '34'
      depth5:
        '@type': CommandQWOP
        distribution:
          type: normal
          mean: 5.0
          standardDeviation: 1.0
        none: '0'
      depth6:
        '@type': CommandQWOP
        distribution:
          type: normal
          mean: 5.0
          standardDeviation: 1.0
        none: '0'
      depth7:
        '@type': CommandQWOP
        distribution:
          type: normal
          mean: 5.0
          standardDeviation: 1.0
        none: '0'
      depth8:
        '@type': CommandQWOP
        distribution:
          type: normal
          mean: 5.0
          standardDeviation: 1.0
        none: '0'
      depth9:
        '@type': CommandQWOP
        distribution:
          type: normal
          mean: 5.0
          standardDeviation: 1.0
        none: '0'
      depth10:
        '@type': CommandQWOP
        distribution:
          type: normal
          mean: 5.0
          standardDeviation: 1.0
        none: '0'
      depth11:
        '@type': CommandQWOP
        distribution:
          type: normal
          mean: 5.0
          standardDeviation: 1.0
        none: '0'
      depth12:
        '@type': CommandQWOP
        distribution:
          type: normal
          mean: 5.0
          standardDeviation: 1.0
        none: '0'
      depth13:
        '@type': CommandQWOP
        distribution:
          type: normal
          mean: 5.0
          standardDeviation: 1.0
        none: '0'
      depth14:
        '@type': CommandQWOP
        distribution:
          type: normal
          mean: 5.0
          standardDeviation: 1.0
        none: '0'
searchOperations:
- stage:
    type: fixed_games
    numGamesToPlay: 20000000
  game:
    type: default #delay_embedded
    # timestepDelay: 1
    # numDelayedStates: 1
    # stateType: DIFFERENCES
  sampler:
    type: ucb
    evaluationFunction:
      type: constant
      scalingFactor: 0.0
    rolloutPolicy:
      type: decaying_horizon
      evaluationFunction:
        type: distance
        scalingFactor: 1.0
      rolloutActionGenerator:
        type: fixed_sequence
        repeatedActions:
        - '@type': CommandQWOP
          distribution:
            type: normal
            mean: 8.0
            standardDeviation: 2.0
          none: '6 7 8 9 10 11 12 13 14 15 16 17'
        - '@type': CommandQWOP
          distribution:
            type: normal
            mean: 4.0
            standardDeviation: 3.0
          w: '1 2 3 4 5 6 7 8'
        - '@type': CommandQWOP
          distribution:
            type: normal
            mean: 9.0
            standardDeviation: 3.0
          wo: '1 2 3 4 5 6 7 8 9 10'
        - '@type': CommandQWOP
          distribution:
            type: normal
            mean: 4.0
            standardDeviation: 3.0
          w: '1 2 3 4 5 6 7 8'
        - '@type': CommandQWOP
          distribution:
            type: normal
            mean: 4.0
            standardDeviation: 3.0
          wo: '1 2 3 4 5 6'
        - '@type': CommandQWOP
          distribution:
            type: normal
            mean: 4.0
            standardDeviation: 3.0
          w: '1 2 3 4 5 6 7 8'
        - '@type': CommandQWOP
          distribution:
            type: normal
            mean: 4.0
            standardDeviation: 3.0
          wo: '1 2 3 4 5 6'
        - '@type': CommandQWOP
          distribution:
            type: normal
            mean: 8.0
            standardDeviation: 2.0
          none: '6 7 8 9 10 11 12 13 14 15 16 17'
        - '@type': CommandQWOP
          distribution:
            type: normal
            mean: 4.0
            standardDeviation: 3.0
          q: '1 2 3 4 5 6 7 8'
        - '@type': CommandQWOP
          distribution:
            type: normal
            mean: 9.0
            standardDeviation: 3.0
          qp: '1 2 3 4 5 6 7 8 9 10'
        - '@type': CommandQWOP
          distribution:
            type: normal
            mean: 4.0
            standardDeviation: 3.0
          q: '1 2 3 4 5 6 7 8'
        - '@type': CommandQWOP
          distribution:
            type: normal
            mean: 4.0
            standardDeviation: 3.0
          qp: '1 2 3 4 5 6'
        - '@type': CommandQWOP
          distribution:
            type: normal
            mean: 4.0
            standardDeviation: 3.0
          q: '1 2 3 4 5 6 7 8'
        - '@type': CommandQWOP
          distribution:
            type: normal
            mean: 4.0
            standardDeviation: 3.0
          qp: '1 2 3 4 5 6 7 8'
      rolloutController:
        type: random
      maxTimesteps: 150
    valueUpdater:
      type: average
    explorationConstant: 0.1
    explorationRandomFactor: 8
  saver:
    type: null
    saveInterval: 0
    savePath:
  repetitionCount: 0
ui:
  type: full
  maxWorkersToMonitor: 5
  tabbedPanes:
  - type: runner_animated_transformed
    name: Run Animation
  - type: runner_snapshot
    name: StateQWOP Viewer
    numHistoryStatesDisplay: 25
  - type: runner_comparison
    name: StateQWOP Compare
    maxNumStatesToShow: 50
  - type: plot_states
    name: StateQWOP Plots
    numberOfPlots: 6
  - type: futures_pie
    name: Viable Futures
  - type: depth_histogram
    name: Leaf depth distribution
  - type: plot_controls
    name: Controls Plots
    numberOfPlots: 6
  - type: plot_transformed
    transformer:
      type: pca
      transformPCAComponents:
        transformPCAComponents: '0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
          20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
          44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
          68 69 70 71 '
    name: PCA Plots
    plotsPerView: 6
    numberOfPlots: 6
  - type: plot_transformed
    transformer:
      type: autoencoder
      graphFile: src/main/resources/tflow_models/AutoEnc_72to12_6layer.pb
    name: Autoenc Plots
    plotsPerView: 6
    numberOfPlots: 6
  - type: controlled_valfun
    name: ValFun controller
    game:
      type: default #delay_embedded
    #   timestepDelay: 1
    #   numDelayedStates: 1
    #   stateType: DIFFERENCES
    stateNormalizer:
      type: normalizer_stateqwop
      normalizationMethod: RANGE
    modelLocation: src/main/resources/tflow_models
    checkpointLocation: src/main/resources/tflow_models/checkpoints
    actionGenerator: null
