package game.action;

import distributions.Distribution_Normal;
import game.qwop.CommandQWOP;
import tree.node.NodeGameExplorableBase;

import java.util.Set;

public class ActionGenerator_QWOPNominal implements IActionGenerator<CommandQWOP> {

    public int windowAbove = 6;
    public int windowBelow = 4;
    @Override
    public ActionList<CommandQWOP> getPotentialChildActionSet(NodeGameExplorableBase<?, CommandQWOP, ?> parentNode) {
        Action<CommandQWOP> nominalAction = actions[parentNode.getTreeDepth()];// % actions.length]; // TODO mod just to
        // keep out of bounds exception from happening, but otherwise not very sensible thing to do.

        ActionList<CommandQWOP> actionList =
                new ActionList<>(new Distribution_Normal<>(nominalAction.getTimestepsTotal(), 2f));

//        if (parentNode.getTreeDepth() < 10) {
//            actionList.add(nominalAction);
//        } else {
            for (int i = -windowBelow; i < windowAbove + 1; i++) {
                if (i + nominalAction.getTimestepsTotal() > 0) {
                    actionList.add(new Action<>(i + nominalAction.getTimestepsTotal(), nominalAction.getCommand()));
                }
            }
//        }
        return actionList;
    }

    @Override
    public Set<Action<CommandQWOP>> getAllPossibleActions() {
        return null; // TODO
    }

    Action<CommandQWOP>[] actions = new Action[] {
            new Action<>(14, CommandQWOP.NONE),
            new Action<>(10, CommandQWOP.WO),
            new Action<>(1, CommandQWOP.W),
            new Action<>(15, CommandQWOP.NONE),
            new Action<>(7, CommandQWOP.Q),
            new Action<>(17, CommandQWOP.QP),

            new Action<>(9, CommandQWOP.NONE),
            new Action<>(1, CommandQWOP.W),
            new Action<>(13, CommandQWOP.WO),
            new Action<>(2, CommandQWOP.W),
            new Action<>(5, CommandQWOP.WO),
            new Action<>(14, CommandQWOP.NONE), // 7
            new Action<>(4, CommandQWOP.QP),
            new Action<>(4, CommandQWOP.Q),
            new Action<>(5, CommandQWOP.QP),
            new Action<>(3, CommandQWOP.Q),
            new Action<>(6, CommandQWOP.QP),
            new Action<>(1, CommandQWOP.Q),

            new Action<>(9, CommandQWOP.NONE),
            new Action<>(6, CommandQWOP.W),
            new Action<>(3, CommandQWOP.WO),
            new Action<>(3, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(3, CommandQWOP.W), // 3
            new Action<>(5, CommandQWOP.WO), // 5
            new Action<>(1, CommandQWOP.W),
            new Action<>(7, CommandQWOP.NONE), // 7
            new Action<>(3, CommandQWOP.P),
            new Action<>(11, CommandQWOP.QP),
            new Action<>(3, CommandQWOP.Q),
            new Action<>(6, CommandQWOP.QP),
            new Action<>(1, CommandQWOP.Q),

            new Action<>(8, CommandQWOP.NONE),
            new Action<>(12, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(2, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(3, CommandQWOP.W), // 27, 8
            new Action<>(8, CommandQWOP.NONE),
            new Action<>(2, CommandQWOP.Q),
            new Action<>(5, CommandQWOP.QP),
            new Action<>(8, CommandQWOP.Q),
            new Action<>(9, CommandQWOP.QP), // 24, 14

            new Action<>(5, CommandQWOP.NONE),
            new Action<>(6, CommandQWOP.WO),
            new Action<>(5, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(4, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(2, CommandQWOP.W), // 25, 14
            new Action<>(6, CommandQWOP.NONE),
            new Action<>(2, CommandQWOP.Q),
            new Action<>(2, CommandQWOP.QP),
            new Action<>(10, CommandQWOP.Q),
            new Action<>(5, CommandQWOP.QP),
            new Action<>(4, CommandQWOP.Q),
            new Action<>(4, CommandQWOP.QP), // 27, 11

            new Action<>(2, CommandQWOP.NONE),
            new Action<>(1, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(5, CommandQWOP.W),
            new Action<>(3, CommandQWOP.WO),
            new Action<>(2, CommandQWOP.W),
            new Action<>(9, CommandQWOP.WO), // 24, 16
            new Action<>(1, CommandQWOP.NONE),
            new Action<>(4, CommandQWOP.QP),
            new Action<>(7, CommandQWOP.Q),
            new Action<>(3, CommandQWOP.QP),
            new Action<>(4, CommandQWOP.Q),
            new Action<>(6, CommandQWOP.QP),
            new Action<>(1, CommandQWOP.Q), // 25, 13

            new Action<>(6, CommandQWOP.NONE),
            new Action<>(14, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(10, CommandQWOP.W),
            new Action<>(1, CommandQWOP.WO),
            new Action<>(5, CommandQWOP.O), // 34, 5
            new Action<>(8, CommandQWOP.NONE),
            new Action<>(17, CommandQWOP.Q),
            new Action<>(10, CommandQWOP.QP), // 27, 10

            new Action<>(9, CommandQWOP.NONE),
            new Action<>(1, CommandQWOP.O),
            new Action<>(3, CommandQWOP.WO),
            new Action<>(11, CommandQWOP.W),
            new Action<>(2, CommandQWOP.WO),
            new Action<>(5, CommandQWOP.W),
            new Action<>(4, CommandQWOP.NONE),
            new Action<>(5, CommandQWOP.O),
            new Action<>(11, CommandQWOP.NONE),
            new Action<>(8, CommandQWOP.Q),
            new Action<>(4, CommandQWOP.QP),
            new Action<>(7, CommandQWOP.Q),
            new Action<>(4, CommandQWOP.QP),
            new Action<>(2, CommandQWOP.Q),
            new Action<>(4, CommandQWOP.QP),

            new Action<>(10, CommandQWOP.NONE),
            new Action<>(1, CommandQWOP.W),
            new Action<>(8, CommandQWOP.WO),
            new Action<>(6, CommandQWOP.W),
            new Action<>(3, CommandQWOP.WO),
            new Action<>(3, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(15, CommandQWOP.NONE),
            new Action<>(3, CommandQWOP.Q),
            new Action<>(7, CommandQWOP.QP),
            new Action<>(9, CommandQWOP.Q),
            new Action<>(6, CommandQWOP.QP),

            new Action<>(8, CommandQWOP.NONE),
            new Action<>(7, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(4, CommandQWOP.W),
            new Action<>(2, CommandQWOP.WO),
            new Action<>(5, CommandQWOP.W),
            new Action<>(3, CommandQWOP.WO),
            new Action<>(1, CommandQWOP.O),
            new Action<>(6, CommandQWOP.NONE),
            new Action<>(1, CommandQWOP.Q),
            new Action<>(3, CommandQWOP.QP),
            new Action<>(12, CommandQWOP.Q),
            new Action<>(4, CommandQWOP.QP),
            new Action<>(5, CommandQWOP.Q),
            new Action<>(1, CommandQWOP.QP),
            new Action<>(2, CommandQWOP.P),

            new Action<>(12, CommandQWOP.NONE),
            new Action<>(1, CommandQWOP.W),
            new Action<>(8, CommandQWOP.WO),
            new Action<>(2, CommandQWOP.W),
            new Action<>(5, CommandQWOP.WO),
            new Action<>(4, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(1, CommandQWOP.O),
            new Action<>(4, CommandQWOP.NONE),
            new Action<>(5, CommandQWOP.Q),
            new Action<>(1, CommandQWOP.QP),
            new Action<>(5, CommandQWOP.Q),
            new Action<>(4, CommandQWOP.QP),
            new Action<>(2, CommandQWOP.Q),
            new Action<>(12, CommandQWOP.QP),
            new Action<>(1, CommandQWOP.Q),

            new Action<>(2, CommandQWOP.NONE),
            new Action<>(2, CommandQWOP.W),
            new Action<>(11, CommandQWOP.WO),
            new Action<>(2, CommandQWOP.W),
            new Action<>(8, CommandQWOP.WO),
            new Action<>(1, CommandQWOP.W),
            new Action<>(14, CommandQWOP.NONE),
            new Action<>(1, CommandQWOP.P),
            new Action<>(8, CommandQWOP.QP),
            new Action<>(7, CommandQWOP.Q),
            new Action<>(8, CommandQWOP.QP),
            new Action<>(2, CommandQWOP.Q),

            new Action<>(6, CommandQWOP.NONE),
            new Action<>(3, CommandQWOP.WO),
            new Action<>(11, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(4, CommandQWOP.W),
            new Action<>(3, CommandQWOP.WO),
            new Action<>(2, CommandQWOP.O),
            new Action<>(12, CommandQWOP.NONE),
            new Action<>(4, CommandQWOP.QP),
            new Action<>(15, CommandQWOP.Q),
            new Action<>(5, CommandQWOP.QP),

            new Action<>(15, CommandQWOP.NONE),
            new Action<>(7, CommandQWOP.W),
            new Action<>(7, CommandQWOP.WO),
            new Action<>(3, CommandQWOP.W),
            new Action<>(3, CommandQWOP.WO),
            new Action<>(4, CommandQWOP.W),
            new Action<>(1, CommandQWOP.WO),
            new Action<>(2, CommandQWOP.O),
            new Action<>(7, CommandQWOP.NONE),
            new Action<>(8, CommandQWOP.Q),
            new Action<>(4, CommandQWOP.QP),
            new Action<>(5, CommandQWOP.Q),
            new Action<>(8, CommandQWOP.QP),
            new Action<>(2, CommandQWOP.Q),

            new Action<>(10, CommandQWOP.NONE),
            new Action<>(3, CommandQWOP.W),
            new Action<>(12, CommandQWOP.WO),
            new Action<>(5, CommandQWOP.W),
            new Action<>(5, CommandQWOP.WO),
            new Action<>(3, CommandQWOP.NONE),
            new Action<>(2, CommandQWOP.QP),
            new Action<>(5, CommandQWOP.Q),
            new Action<>(4, CommandQWOP.QP),
            new Action<>(2, CommandQWOP.Q),
            new Action<>(12, CommandQWOP.QP),
            new Action<>(1, CommandQWOP.Q),

            new Action<>(5, CommandQWOP.NONE),
            new Action<>(1, CommandQWOP.W),
            new Action<>(5, CommandQWOP.WO),
            new Action<>(5, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(4, CommandQWOP.W),
            new Action<>(2, CommandQWOP.WO),
            new Action<>(3, CommandQWOP.O),
            new Action<>(2, CommandQWOP.NONE),
            new Action<>(5, CommandQWOP.QP),
            new Action<>(5, CommandQWOP.Q),
            new Action<>(4, CommandQWOP.QP),
            new Action<>(4, CommandQWOP.Q),
            new Action<>(7, CommandQWOP.QP),
            new Action<>(1, CommandQWOP.Q),

            new Action<>(4, CommandQWOP.NONE),
            new Action<>(14, CommandQWOP.WO),
            new Action<>(2, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(4, CommandQWOP.W),
            new Action<>(2, CommandQWOP.WO),
            new Action<>(2, CommandQWOP.O),
            new Action<>(5, CommandQWOP.NONE),
            new Action<>(12, CommandQWOP.Q),
            new Action<>(4, CommandQWOP.QP),
            new Action<>(2, CommandQWOP.Q),
            new Action<>(15, CommandQWOP.QP),
            new Action<>(2, CommandQWOP.Q),

            new Action<>(2, CommandQWOP.NONE),
            new Action<>(1, CommandQWOP.W),
            new Action<>(9, CommandQWOP.WO),
            new Action<>(5, CommandQWOP.W),
            new Action<>(3, CommandQWOP.WO),
            new Action<>(2, CommandQWOP.W),
            new Action<>(6, CommandQWOP.WO),
            new Action<>(2, CommandQWOP.W),
            new Action<>(15, CommandQWOP.NONE),
            new Action<>(13, CommandQWOP.QP),
            new Action<>(4, CommandQWOP.Q),
            new Action<>(5, CommandQWOP.QP),

            new Action<>(5, CommandQWOP.NONE),
            new Action<>(11, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(3, CommandQWOP.W),
            new Action<>(11, CommandQWOP.WO),
            new Action<>(1, CommandQWOP.O),
            new Action<>(1, CommandQWOP.NONE),
            new Action<>(2, CommandQWOP.Q),
            new Action<>(5, CommandQWOP.QP),
            new Action<>(10, CommandQWOP.Q),
            new Action<>(5, CommandQWOP.QP),
            new Action<>(1, CommandQWOP.Q),

            new Action<>(7, CommandQWOP.NONE),
            new Action<>(3, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(7, CommandQWOP.W),
            new Action<>(3, CommandQWOP.WO),
            new Action<>(5, CommandQWOP.W),
            new Action<>(12, CommandQWOP.NONE),
            new Action<>(15, CommandQWOP.Q),
            new Action<>(3, CommandQWOP.QP),
            new Action<>(3, CommandQWOP.Q),
            new Action<>(4, CommandQWOP.QP),

            new Action<>(9, CommandQWOP.NONE),
            new Action<>(2, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(6, CommandQWOP.W),
            new Action<>(3, CommandQWOP.WO),
            new Action<>(4, CommandQWOP.W),
            new Action<>(2, CommandQWOP.WO),
            new Action<>(5, CommandQWOP.W),
            new Action<>(3, CommandQWOP.O),
            new Action<>(8, CommandQWOP.NONE),
            new Action<>(2, CommandQWOP.Q),
            new Action<>(3, CommandQWOP.QP),
            new Action<>(12, CommandQWOP.Q),
            new Action<>(7, CommandQWOP.QP),
            new Action<>(1, CommandQWOP.Q),
            new Action<>(5, CommandQWOP.NONE),
            new Action<>(2, CommandQWOP.O),
            new Action<>(8, CommandQWOP.WO),
            new Action<>(4, CommandQWOP.W),
            new Action<>(5, CommandQWOP.WO),
            new Action<>(3, CommandQWOP.W),
            new Action<>(1, CommandQWOP.WO),
            new Action<>(1, CommandQWOP.O),
            new Action<>(6, CommandQWOP.NONE),
            new Action<>(3, CommandQWOP.Q),
            new Action<>(7, CommandQWOP.QP),
            new Action<>(5, CommandQWOP.Q),
            new Action<>(10, CommandQWOP.QP),
            new Action<>(2, CommandQWOP.Q),
            new Action<>(10, CommandQWOP.NONE),
            new Action<>(1, CommandQWOP.W),
            new Action<>(11, CommandQWOP.WO),
            new Action<>(5, CommandQWOP.W),
            new Action<>(5, CommandQWOP.WO),
            new Action<>(1, CommandQWOP.W),
            new Action<>(9, CommandQWOP.NONE),
            new Action<>(11, CommandQWOP.QP),
            new Action<>(5, CommandQWOP.Q),
            new Action<>(9, CommandQWOP.QP),
            new Action<>(6, CommandQWOP.NONE),
            new Action<>(2, CommandQWOP.W),
            new Action<>(8, CommandQWOP.WO),
            new Action<>(4, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(5, CommandQWOP.W),
            new Action<>(6, CommandQWOP.NONE),
            new Action<>(4, CommandQWOP.QP),
            new Action<>(12, CommandQWOP.Q),
            new Action<>(9, CommandQWOP.QP),
            new Action<>(11, CommandQWOP.NONE),
            new Action<>(3, CommandQWOP.W),
            new Action<>(9, CommandQWOP.WO),
            new Action<>(7, CommandQWOP.W),
            new Action<>(5, CommandQWOP.WO),
            new Action<>(15, CommandQWOP.NONE),
            new Action<>(1, CommandQWOP.Q),
            new Action<>(10, CommandQWOP.QP),
            new Action<>(5, CommandQWOP.Q),
            new Action<>(9, CommandQWOP.QP),
            new Action<>(4, CommandQWOP.NONE),
            new Action<>(6, CommandQWOP.WO),
            new Action<>(3, CommandQWOP.W),
            new Action<>(2, CommandQWOP.WO),
            new Action<>(5, CommandQWOP.W),
            new Action<>(5, CommandQWOP.WO),
            new Action<>(3, CommandQWOP.W),
            new Action<>(12, CommandQWOP.NONE),
            new Action<>(10, CommandQWOP.QP),
            new Action<>(5, CommandQWOP.Q),
            new Action<>(5, CommandQWOP.QP),
            new Action<>(3, CommandQWOP.Q),
            new Action<>(7, CommandQWOP.NONE),
            new Action<>(13, CommandQWOP.WO),
            new Action<>(6, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(1, CommandQWOP.W),
            new Action<>(12, CommandQWOP.NONE),
            new Action<>(4, CommandQWOP.Q),
            new Action<>(11, CommandQWOP.QP),
            new Action<>(4, CommandQWOP.Q),
            new Action<>(5, CommandQWOP.QP),
            new Action<>(1, CommandQWOP.Q),
            new Action<>(9, CommandQWOP.NONE),
            new Action<>(5, CommandQWOP.WO),
            new Action<>(5, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(4, CommandQWOP.W),
            new Action<>(5, CommandQWOP.WO),
            new Action<>(7, CommandQWOP.NONE),
            new Action<>(10, CommandQWOP.Q),
            new Action<>(4, CommandQWOP.QP),
            new Action<>(2, CommandQWOP.Q),
            new Action<>(7, CommandQWOP.QP),
            new Action<>(2, CommandQWOP.Q),
            new Action<>(5, CommandQWOP.QP),
            new Action<>(8, CommandQWOP.NONE),
            new Action<>(1, CommandQWOP.W),
            new Action<>(10, CommandQWOP.WO),
            new Action<>(4, CommandQWOP.W),
            new Action<>(3, CommandQWOP.WO),
            new Action<>(4, CommandQWOP.W),
            new Action<>(9, CommandQWOP.NONE),
            new Action<>(1, CommandQWOP.P),
            new Action<>(16, CommandQWOP.Q),
            new Action<>(5, CommandQWOP.QP),
            new Action<>(2, CommandQWOP.Q),
            new Action<>(10, CommandQWOP.NONE),
            new Action<>(13, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(4, CommandQWOP.W),
            new Action<>(4, CommandQWOP.WO),
            new Action<>(1, CommandQWOP.O),
            new Action<>(4, CommandQWOP.NONE),
            new Action<>(2, CommandQWOP.QP),
            new Action<>(5, CommandQWOP.Q),
            new Action<>(5, CommandQWOP.QP),
            new Action<>(4, CommandQWOP.Q),
            new Action<>(10, CommandQWOP.QP),
            new Action<>(1, CommandQWOP.P),
            new Action<>(4, CommandQWOP.NONE),
            new Action<>(2, CommandQWOP.O),
            new Action<>(19, CommandQWOP.WO),
            new Action<>(1, CommandQWOP.O),
            new Action<>(2, CommandQWOP.P),
            new Action<>(17, CommandQWOP.QP)
    };
}
