# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: densedata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='densedata.proto',
  package='data',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x64\x65nsedata.proto\x12\x04\x64\x61ta\"\xc1\x08\n\x07\x44\x61taSet\x12*\n\tdenseData\x18\x01 \x03(\x0b\x32\x17.data.DataSet.DenseData\x1a\x89\x08\n\tDenseData\x12,\n\x05state\x18\x01 \x03(\x0b\x32\x1d.data.DataSet.DenseData.StateQWOP\x12.\n\x06\x61\x63tion\x18\x02 \x03(\x0b\x32\x1e.data.DataSet.DenseData.Action\x1a\xaf\x06\n\x05State\x12\x39\n\x04\x62ody\x18\x01 \x02(\x0b\x32+.data.DataSet.DenseData.StateQWOP.StateVariable6D\x12;\n\x06rthigh\x18\x02 \x02(\x0b\x32+.data.DataSet.DenseData.StateQWOP.StateVariable6D\x12;\n\x06lthigh\x18\x03 \x02(\x0b\x32+.data.DataSet.DenseData.StateQWOP.StateVariable6D\x12:\n\x05rcalf\x18\x04 \x02(\x0b\x32+.data.DataSet.DenseData.StateQWOP.StateVariable6D\x12:\n\x05lcalf\x18\x05 \x02(\x0b\x32+.data.DataSet.DenseData.StateQWOP.StateVariable6D\x12:\n\x05rfoot\x18\x06 \x02(\x0b\x32+.data.DataSet.DenseData.StateQWOP.StateVariable6D\x12:\n\x05lfoot\x18\x07 \x02(\x0b\x32+.data.DataSet.DenseData.StateQWOP.StateVariable6D\x12:\n\x05ruarm\x18\x08 \x02(\x0b\x32+.data.DataSet.DenseData.StateQWOP.StateVariable6D\x12:\n\x05luarm\x18\t \x02(\x0b\x32+.data.DataSet.DenseData.StateQWOP.StateVariable6D\x12:\n\x05rlarm\x18\n \x02(\x0b\x32+.data.DataSet.DenseData.StateQWOP.StateVariable6D\x12:\n\x05llarm\x18\x0b \x02(\x0b\x32+.data.DataSet.DenseData.StateQWOP.StateVariable6D\x12\x39\n\x04head\x18\x0c \x02(\x0b\x32+.data.DataSet.DenseData.StateQWOP.StateVariable6D\x1aV\n\rStateVariable6D\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\n\n\x02th\x18\x03 \x02(\x02\x12\n\n\x02\x64x\x18\x04 \x02(\x02\x12\n\n\x02\x64y\x18\x05 \x02(\x02\x12\x0b\n\x03\x64th\x18\x06 \x02(\x02\x1al\n\x06\x41\x63tion\x12\t\n\x01Q\x18\x01 \x02(\x08\x12\t\n\x01W\x18\x02 \x02(\x08\x12\t\n\x01O\x18\x03 \x02(\x08\x12\t\n\x01P\x18\x04 \x02(\x08\x12\x17\n\x0f\x61\x63tionTimesteps\x18\x05 \x01(\x05\x12\x1d\n\x15\x63urrentActionTimestep\x18\x06 \x01(\x05\x42\x17\n\x04\x64\x61taB\x0f\x44\x65nseDataProtos')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DATASET_DENSEDATA_STATE_STATEVARIABLE = _descriptor.Descriptor(
  name='StateVariable6D',
  full_name='data.DataSet.DenseData.StateQWOP.StateVariable6D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='data.DataSet.DenseData.StateQWOP.StateVariable6D.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='data.DataSet.DenseData.StateQWOP.StateVariable6D.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='th', full_name='data.DataSet.DenseData.StateQWOP.StateVariable6D.th', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dx', full_name='data.DataSet.DenseData.StateQWOP.StateVariable6D.dx', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dy', full_name='data.DataSet.DenseData.StateQWOP.StateVariable6D.dy', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dth', full_name='data.DataSet.DenseData.StateQWOP.StateVariable6D.dth', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=919,
  serialized_end=1005,
)

_DATASET_DENSEDATA_STATE = _descriptor.Descriptor(
  name='StateQWOP',
  full_name='data.DataSet.DenseData.StateQWOP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='data.DataSet.DenseData.StateQWOP.body', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rthigh', full_name='data.DataSet.DenseData.StateQWOP.rthigh', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lthigh', full_name='data.DataSet.DenseData.StateQWOP.lthigh', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rcalf', full_name='data.DataSet.DenseData.StateQWOP.rcalf', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lcalf', full_name='data.DataSet.DenseData.StateQWOP.lcalf', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rfoot', full_name='data.DataSet.DenseData.StateQWOP.rfoot', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lfoot', full_name='data.DataSet.DenseData.StateQWOP.lfoot', index=6,
      number=7, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ruarm', full_name='data.DataSet.DenseData.StateQWOP.ruarm', index=7,
      number=8, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='luarm', full_name='data.DataSet.DenseData.StateQWOP.luarm', index=8,
      number=9, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rlarm', full_name='data.DataSet.DenseData.StateQWOP.rlarm', index=9,
      number=10, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='llarm', full_name='data.DataSet.DenseData.StateQWOP.llarm', index=10,
      number=11, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='head', full_name='data.DataSet.DenseData.StateQWOP.head', index=11,
      number=12, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATASET_DENSEDATA_STATE_STATEVARIABLE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=1005,
)

_DATASET_DENSEDATA_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='data.DataSet.DenseData.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Q', full_name='data.DataSet.DenseData.Action.Q', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='W', full_name='data.DataSet.DenseData.Action.W', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='O', full_name='data.DataSet.DenseData.Action.O', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='P', full_name='data.DataSet.DenseData.Action.P', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actionTimesteps', full_name='data.DataSet.DenseData.Action.actionTimesteps', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currentActionTimestep', full_name='data.DataSet.DenseData.Action.currentActionTimestep', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1007,
  serialized_end=1115,
)

_DATASET_DENSEDATA = _descriptor.Descriptor(
  name='DenseData',
  full_name='data.DataSet.DenseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='data.DataSet.DenseData.state', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command', full_name='data.DataSet.DenseData.command', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATASET_DENSEDATA_STATE, _DATASET_DENSEDATA_ACTION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=1115,
)

_DATASET = _descriptor.Descriptor(
  name='DataSet',
  full_name='data.DataSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='denseData', full_name='data.DataSet.denseData', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATASET_DENSEDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=1115,
)

_DATASET_DENSEDATA_STATE_STATEVARIABLE.containing_type = _DATASET_DENSEDATA_STATE
_DATASET_DENSEDATA_STATE.fields_by_name['body'].message_type = _DATASET_DENSEDATA_STATE_STATEVARIABLE
_DATASET_DENSEDATA_STATE.fields_by_name['rthigh'].message_type = _DATASET_DENSEDATA_STATE_STATEVARIABLE
_DATASET_DENSEDATA_STATE.fields_by_name['lthigh'].message_type = _DATASET_DENSEDATA_STATE_STATEVARIABLE
_DATASET_DENSEDATA_STATE.fields_by_name['rcalf'].message_type = _DATASET_DENSEDATA_STATE_STATEVARIABLE
_DATASET_DENSEDATA_STATE.fields_by_name['lcalf'].message_type = _DATASET_DENSEDATA_STATE_STATEVARIABLE
_DATASET_DENSEDATA_STATE.fields_by_name['rfoot'].message_type = _DATASET_DENSEDATA_STATE_STATEVARIABLE
_DATASET_DENSEDATA_STATE.fields_by_name['lfoot'].message_type = _DATASET_DENSEDATA_STATE_STATEVARIABLE
_DATASET_DENSEDATA_STATE.fields_by_name['ruarm'].message_type = _DATASET_DENSEDATA_STATE_STATEVARIABLE
_DATASET_DENSEDATA_STATE.fields_by_name['luarm'].message_type = _DATASET_DENSEDATA_STATE_STATEVARIABLE
_DATASET_DENSEDATA_STATE.fields_by_name['rlarm'].message_type = _DATASET_DENSEDATA_STATE_STATEVARIABLE
_DATASET_DENSEDATA_STATE.fields_by_name['llarm'].message_type = _DATASET_DENSEDATA_STATE_STATEVARIABLE
_DATASET_DENSEDATA_STATE.fields_by_name['head'].message_type = _DATASET_DENSEDATA_STATE_STATEVARIABLE
_DATASET_DENSEDATA_STATE.containing_type = _DATASET_DENSEDATA
_DATASET_DENSEDATA_ACTION.containing_type = _DATASET_DENSEDATA
_DATASET_DENSEDATA.fields_by_name['state'].message_type = _DATASET_DENSEDATA_STATE
_DATASET_DENSEDATA.fields_by_name['command'].message_type = _DATASET_DENSEDATA_ACTION
_DATASET_DENSEDATA.containing_type = _DATASET
_DATASET.fields_by_name['denseData'].message_type = _DATASET_DENSEDATA
DESCRIPTOR.message_types_by_name['DataSet'] = _DATASET

DataSet = _reflection.GeneratedProtocolMessageType('DataSet', (_message.Message,), dict(

  DenseData = _reflection.GeneratedProtocolMessageType('DenseData', (_message.Message,), dict(

    State = _reflection.GeneratedProtocolMessageType('StateQWOP', (_message.Message,), dict(

      StateVariable = _reflection.GeneratedProtocolMessageType('StateVariable6D', (_message.Message,), dict(
        DESCRIPTOR = _DATASET_DENSEDATA_STATE_STATEVARIABLE,
        __module__ = 'densedata_pb2'
        # @@protoc_insertion_point(class_scope:data.DataSet.DenseData.StateQWOP.StateVariable6D)
        ))
      ,
      DESCRIPTOR = _DATASET_DENSEDATA_STATE,
      __module__ = 'densedata_pb2'
      # @@protoc_insertion_point(class_scope:data.DataSet.DenseData.StateQWOP)
      ))
    ,

    Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), dict(
      DESCRIPTOR = _DATASET_DENSEDATA_ACTION,
      __module__ = 'densedata_pb2'
      # @@protoc_insertion_point(class_scope:data.DataSet.DenseData.Action)
      ))
    ,
    DESCRIPTOR = _DATASET_DENSEDATA,
    __module__ = 'densedata_pb2'
    # @@protoc_insertion_point(class_scope:data.DataSet.DenseData)
    ))
  ,
  DESCRIPTOR = _DATASET,
  __module__ = 'densedata_pb2'
  # @@protoc_insertion_point(class_scope:data.DataSet)
  ))
_sym_db.RegisterMessage(DataSet)
_sym_db.RegisterMessage(DataSet.DenseData)
_sym_db.RegisterMessage(DataSet.DenseData.State)
_sym_db.RegisterMessage(DataSet.DenseData.State.StateVariable)
_sym_db.RegisterMessage(DataSet.DenseData.Action)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\004dataB\017DenseDataProtos'))
# @@protoc_insertion_point(module_scope)
