// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feature.proto

package data;

public interface FeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.Feature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .tensorflow.BytesList bytes_list = 1;</code>
   */
  data.BytesList getBytesList();
  /**
   * <code>optional .tensorflow.BytesList bytes_list = 1;</code>
   */
  data.BytesListOrBuilder getBytesListOrBuilder();

  /**
   * <code>optional .tensorflow.FloatList float_list = 2;</code>
   */
  data.FloatList getFloatList();
  /**
   * <code>optional .tensorflow.FloatList float_list = 2;</code>
   */
  data.FloatListOrBuilder getFloatListOrBuilder();

  /**
   * <code>optional .tensorflow.Int64List int64_list = 3;</code>
   */
  data.Int64List getInt64List();
  /**
   * <code>optional .tensorflow.Int64List int64_list = 3;</code>
   */
  data.Int64ListOrBuilder getInt64ListOrBuilder();

  public data.Feature.KindCase getKindCase();
}
