// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feature.proto

package data;

public interface FeatureListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.FeatureList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tensorflow.Feature feature = 1;</code>
   */
  java.util.List<data.Feature> 
      getFeatureList();
  /**
   * <code>repeated .tensorflow.Feature feature = 1;</code>
   */
  data.Feature getFeature(int index);
  /**
   * <code>repeated .tensorflow.Feature feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <code>repeated .tensorflow.Feature feature = 1;</code>
   */
  java.util.List<? extends data.FeatureOrBuilder> 
      getFeatureOrBuilderList();
  /**
   * <code>repeated .tensorflow.Feature feature = 1;</code>
   */
  data.FeatureOrBuilder getFeatureOrBuilder(
      int index);
}
